<a href="https://colab.research.google.com/github/Joeaviator/POKEMON_PREPROCESSIG/blob/main/POKEMON_PREPROCESSING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [7]:
from google.colab import files
file = files.upload()

Saving pokemon_data.csv to pokemon_data.csv

In [8]:
df=pd.read_csv('pokemon_data.csv')
df.head()

,Unnamed: 0,against_water,attack,capture_rate,classfication,defense,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,0,0.5,49,45,Seed Pokémon,49,65,65,45,grass,poison,6.9,1,0
1,1,0.5,62,45,Seed Pokémon,63,80,80,60,grass,poison,13.0,1,0
2,2,0.5,100,45,Seed Pokémon,123,122,120,80,grass,poison,100.0,1,0
3,5,2.0,104,45,Flame Pokémon,78,159,115,100,fire,flying,90.5,1,0
4,11,1.0,45,45,Butterfly Pokémon,50,90,80,70,bug,flying,32.0,1,0

In [9]:
df.isnull().sum()

Unnamed: 0       0
against_water    0
attack           0
capture_rate     0
classfication    0
defense          0
sp_attack        0
sp_defense       0
speed            0
type1            0
type2            0
weight_kg        0
generation       0
is_legendary     0
dtype: int64

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     398 non-null    int64
 1   against_water  398 non-null    float64
 2   attack         398 non-null    int64
 3   capture_rate   398 non-null    object
 4   classfication  398 non-null    object
 5   defense        398 non-null    int64
 6   sp_attack      398 non-null    int64
 7   sp_defense     398 non-null    int64
 8   speed          398 non-null    int64
 9   type1          398 non-null    object
 10  type2          398 non-null    object
 11  weight_kg      398 non-null    float64
 12  generation     398 non-null    int64
 13  is_legendary   398 non-null    int64
dtypes: float64(2), int64(8), object(4)
memory usage: 43.7+ KB

In [11]:
df=df.drop('Unnamed: 0',axis=1)

In [12]:
df.head()

,against_water,attack,capture_rate,classfication,defense,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,0.5,49,45,Seed Pokémon,49,65,65,45,grass,poison,6.9,1,0
1,0.5,62,45,Seed Pokémon,63,80,80,60,grass,poison,13.0,1,0
2,0.5,100,45,Seed Pokémon,123,122,120,80,grass,poison,100.0,1,0
3,2.0,104,45,Flame Pokémon,78,159,115,100,fire,flying,90.5,1,0
4,1.0,45,45,Butterfly Pokémon,50,90,80,70,bug,flying,32.0,1,0

In [13]:
le=LabelEncoder()
df['type1']=le.fit_transform(df['type1'])
df['type2']=le.fit_transform(df['type2'])
df['classfication']=le.fit_transform(df['classfication'])

In [14]:
x=df.drop('is_legendary', axis=1)
y=df['is_legendary']

In [15]:
df.head()

,against_water,attack,capture_rate,classfication,defense,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,0.5,49,45,235,49,65,65,45,9,13,6.9,1,0
1,0.5,62,45,235,63,80,80,60,9,13,13.0,1,0
2,0.5,100,45,235,123,122,120,80,9,13,100.0,1,0
3,2.0,104,45,102,78,159,115,100,6,7,90.5,1,0
4,1.0,45,45,44,50,90,80,70,0,7,32.0,1,0

In [16]:
x['capture_rate'] = x['capture_rate'].astype(str).str.extract('(\\d+)').astype(float)
x['capture_rate'] = x['capture_rate'].fillna(x['capture_rate'].mean())
x=StandardScaler().fit_transform(x)

In [17]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2,random_state=42)

In [18]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from sklearn.metrics import accuracy_score,confusion_matrix

In [23]:
model=Sequential()
#input layer
model.add(Dense(6,kernel_initializer='he_uniform',activation='relu',input_dim=12))
#Dropout Layer
model.add(Dropout(0.3))
#Hidden Layer
model.add(Dense(6,kernel_initializer='he_uniform',activation='relu'))
#Dropout layer
model.add(Dropout(0.3))
#Output Layer
model.add(Dense(1,kernel_initializer='glorot_uniform',activation='sigmoid'))
print("Model Built Sucessfully")

Model Built Sucessfully

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [24]:
model.compile(optimizer='Adamax', loss='binary_crossentropy', metrics=['accuracy'])
print("Compilation Successful")

Compilation Successful

In [25]:
t_model=model.fit(x_train,y_train,batch_size=10,epochs=100)

Epoch 1/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6447 - loss: 0.7019
Epoch 2/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7044 - loss: 0.6903
Epoch 3/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7358 - loss: 0.6870
Epoch 4/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7547 - loss: 0.6459
Epoch 5/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7579 - loss: 0.6454
Epoch 6/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7893 - loss: 0.6273
Epoch 7/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7925 - loss: 0.5988
Epoch 8/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8302 - loss: 0.5710
Epoch 9/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8491 - loss: 0.5521
Epoch 10/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8208 - loss: 0.5855
Epoch 11/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8396 - loss: 0.5656
Epoch 12/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8553 - loss: 0.5587
Epoch 13/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8679 - loss: 0.5839
Epoch 14/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8648 - loss: 0.5350
Epoch 15/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8805 - loss: 0.5020
Epoch 16/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8742 - loss: 0.4907
Epoch 17/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8616 - loss: 0.4807
Epoch 18/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8805 - loss: 0.4774
Epoch 19/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8711 - loss: 0.4827
Epoch 20/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8711 - loss: 0.4758
Epoch 21/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8616 - loss: 0.4888
Epoch 22/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8899 - loss: 0.4377
Epoch 23/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8868 - loss: 0.3987
Epoch 24/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8805 - loss: 0.4398
Epoch 25/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8899 - loss: 0.4302
Epoch 26/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8648 - loss: 0.4390
Epoch 27/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8836 - loss: 0.4370
Epoch 28/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8805 - loss: 0.4095
Epoch 29/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8836 - loss: 0.4017
Epoch 30/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8774 - loss: 0.3912
Epoch 31/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8805 - loss: 0.3831
Epoch 32/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8774 - loss: 0.4071
Epoch 33/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8836 - loss: 0.4214
Epoch 34/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8868 - loss: 0.3897
Epoch 35/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8774 - loss: 0.4128
Epoch 36/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8836 - loss: 0.3574
Epoch 37/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8899 - loss: 0.3694
Epoch 38/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8868 - loss: 0.3831
Epoch 39/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8899 - loss: 0.3613
Epoch 40/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8836 - loss: 0.3707
Epoch 41/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8899 - loss: 0.3559
Epoch 42/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8868 - loss: 0.3520
Epoch 43/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8868 - loss: 0.3439
Epoch 44/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8868 - loss: 0.3685
Epoch 45/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8836 - loss: 0.3681
Epoch 46/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8868 - loss: 0.3748
Epoch 47/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8836 - loss: 0.3792
Epoch 48/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8868 - loss: 0.3562
Epoch 49/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8868 - loss: 0.3725
Epoch 50/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8899 - loss: 0.3536
Epoch 51/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8868 - loss: 0.3734
Epoch 52/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8836 - loss: 0.3399
Epoch 53/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8805 - loss: 0.3591
Epoch 54/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8836 - loss: 0.3371
Epoch 55/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8868 - loss: 0.3575
Epoch 56/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8868 - loss: 0.3466
Epoch 57/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8868 - loss: 0.3280
Epoch 58/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8836 - loss: 0.3468
Epoch 59/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8868 - loss: 0.3383
Epoch 60/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8868 - loss: 0.3440
Epoch 61/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8868 - loss: 0.3275
Epoch 62/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8836 - loss: 0.3352
Epoch 63/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8868 - loss: 0.3362
Epoch 64/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8868 - loss: 0.3311
Epoch 65/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8836 - loss: 0.3290
Epoch 66/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8868 - loss: 0.3360
Epoch 67/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8868 - loss: 0.3103
Epoch 68/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8868 - loss: 0.2988
Epoch 69/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8868 - loss: 0.3205
Epoch 70/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8868 - loss: 0.3252
Epoch 71/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8868 - loss: 0.3147
Epoch 72/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8868 - loss: 0.3071
Epoch 73/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8868 - loss: 0.3220
Epoch 74/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8868 - loss: 0.3268
Epoch 75/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8868 - loss: 0.3348
Epoch 76/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8899 - loss: 0.3060
Epoch 77/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8868 - loss: 0.3091
Epoch 78/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8868 - loss: 0.2865
Epoch 79/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8836 - loss: 0.3170
Epoch 80/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8868 - loss: 0.3094
Epoch 81/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8868 - loss: 0.3256
Epoch 82/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8868 - loss: 0.3206
Epoch 83/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8868 - loss: 0.3023
Epoch 84/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8868 - loss: 0.3231
Epoch 85/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8868 - loss: 0.3127
Epoch 86/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8868 - loss: 0.2942
Epoch 87/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8868 - loss: 0.3040
Epoch 88/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8868 - loss: 0.3251
Epoch 89/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8868 - loss: 0.3073
Epoch 90/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8868 - loss: 0.3163
Epoch 91/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8868 - loss: 0.3036
Epoch 92/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8868 - loss: 0.3282
Epoch 93/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8868 - loss: 0.3132
Epoch 94/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8868 - loss: 0.3017
Epoch 95/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8868 - loss: 0.3171
Epoch 96/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8868 - loss: 0.2947
Epoch 97/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8868 - loss: 0.3024
Epoch 98/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8868 - loss: 0.3210
Epoch 99/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8868 - loss: 0.2946
Epoch 100/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8868 - loss: 0.3015

In [26]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 6)              │            78 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 6)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 6)              │            42 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 6)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │             7 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 383 (1.50 KB)

 Trainable params: 127 (508.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 256 (1.00 KB)

In [27]:
preds=model.predict(x_test)

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

In [28]:
preds

array([[1.81440599e-02],
       [6.78927451e-02],
       [9.59726945e-02],
       [1.80125356e-01],
       [1.88575968e-01],
       [7.51404539e-02],
       [4.36739586e-02],
       [1.58841223e-01],
       [1.31992713e-01],
       [1.68731079e-01],
       [2.31934860e-02],
       [8.81729126e-02],
       [6.29136637e-02],
       [1.23696262e-03],
       [1.79130048e-01],
       [6.34455681e-02],
       [7.73987770e-02],
       [8.12545195e-02],
       [1.75045580e-01],
       [5.92996180e-02],
       [1.76832274e-01],
       [2.41265725e-03],
       [2.53325015e-01],
       [6.40259683e-03],
       [7.41936266e-02],
       [2.48965859e-01],
       [1.36972100e-01],
       [1.13083079e-01],
       [3.96381058e-02],
       [2.36449137e-01],
       [3.90524566e-02],
       [1.06221978e-02],
       [2.55925804e-01],
       [2.35665575e-01],
       [1.08643649e-02],
       [3.81193124e-02],
       [2.40567788e-01],
       [6.61772564e-02],
       [1.16413102e-01],
       [1.52302444e-01],
       [1.19795375e-01],
       [1.30514562e-01],
       [4.29272372e-03],
       [8.92278329e-02],
       [4.46490914e-04],
       [2.33647257e-01],
       [2.47643562e-03],
       [1.26154572e-01],
       [3.58896796e-03],
       [2.45947391e-01],
       [1.06865853e-04],
       [1.54828401e-02],
       [1.55723616e-02],
       [2.15755533e-02],
       [6.78653456e-03],
       [2.60292202e-01],
       [1.43575281e-01],
       [2.50475528e-03],
       [9.67711881e-02],
       [4.04785853e-03],
       [2.07599238e-01],
       [2.69741267e-01],
       [2.65161902e-01],
       [2.73128459e-03],
       [1.77846506e-01],
       [2.64186710e-01],
       [2.30204277e-02],
       [1.55943066e-01],
       [8.20332915e-02],
       [6.69588819e-02],
       [1.26759082e-01],
       [6.94398070e-03],
       [2.72697478e-04],
       [9.36502218e-03],
       [2.66322643e-01],
       [6.71597896e-03],
       [2.07599238e-01],
       [8.23438913e-03],
       [2.36515522e-01],
       [6.50507733e-02]], dtype=float32)

In [29]:
accuracy_score(y_test,preds.round())

0.9

In [30]:
confusion_matrix(y_test,preds.round())

array([[72,  0],
       [ 8,  0]])